theme = "bram"

[editor]
rainbow-brackets = true
line-number = "relative"
true-color = true
auto-pairs = false
terminal.command = "bash"
terminal.args = [ "-c" ]
[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[keys.insert]
"esc" = ["normal_mode", ":format", ":w"]

[keys.normal]
"#" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
S-r = [":sh ysh /home/bram/programs/utils/repl-build"]
S-t = [":sh ysh /home/bram/programs/utils/run-tests"]


[keys.select]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
